services:
  # LibreChat API - FAST LOCAL MODE with local databases
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./images:/app/client/public/images
      - ./client/public/assets:/app/client/public/assets
    environment:
      # Use LOCAL databases for speed (no network latency)
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_API_URL=http://rag_api:8000
      # Add resource limits for better performance
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096

  # MongoDB - Local for SPEED (separate test data from Railway production)
  mongodb:
    restart: always
    volumes:
      - ./data-node-local:/data/db

  # Meilisearch - Local search for SPEED
  meilisearch:
    restart: always
    volumes:
      - ./meili_data_local:/meili_data

  # RAG API - Local for SPEED
  rag_api:
    restart: always

  # VectorDB - Local for SPEED
  vectordb:
    restart: always
