name: Auto Commit and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "Combined Memory Bot"
          git config --global user.email "bot@combinedmemory.com"

      - name: Check for changes
        id: check_changes
        run: |
          git fetch origin main
          if git diff --quiet origin/main HEAD; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Auto commit if changes exist
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git add -A
          git commit -m "Auto-commit: Update configuration files [skip ci]" || echo "No changes to commit"
          git push origin main
